### ISSUE TITLE
add class to the submit button

### ISSUE THREAD

**Issue by micmica** [mbr/flask-bootstrap#116]
I'm using a flask-wtf submit button as follows:

 {{ wtf.form_field(form.submit, button_map={'submit': 'primary'}) }}
I want to add a class like class="shutdown" to the submit button but I can not find anything about that.
Anything to recommend?

**Comment by mbr** [comment]
I would say either hand-layout your form if you need to control like this or use different CSS selectors. What are you trying to achieve overall?

**Comment by micmica** [comment]
Well I have script that works on elements with class shutdown, it's complicate but that script is sending http request and I need to do that for every button I have. 
Since my application has users I need a button for every user that's why I use wtf forms, I just need to add class  shutdown for those buttons. Please tell me you have something on your mind?

**Comment by mbr** [comment]
Assuming you're using something like jquery, you could get the button using a different selector than just the class. Instead of ``$('.shutdown')``, if all of these forms are wrapped inside a specific div, you could do ``$('.div-containig-all-user-ids input[type=submit]')``, for example.

Other than that, you could, I believe, subclass the WTForms widget and add a class that way. Since you have needs that go well beyond a standard form, have a look at laying out a form manually, by rendering fields directly - it's not that complicated.

**Comment by micmica** [comment]
Thank you!
