### ISSUE TITLE
bootstrap_find_resource

### ISSUE THREAD

**Issue by slippers** [mbr/flask-bootstrap#124]

**Comment by mbr** [comment]
Since the issue disappeared, I hope you solved your problem =).

**Comment by slippers** [comment]
think I'm asking the wrong question based on improper assumptions:)  probably making this more difficult than it is:)

i asked on stack overflow.  using url_for would link in my theme css.  beginning to understand that in production environment you would want to use cdn?  i see that i can link to custom themed css as cdn also.  not sure why you would want a cdn at the time of development.

was expecting that if I put files in my local /static/bootstrap/css directory that bootstrap_find_resource would pull from that over what was in site-packages/flask_bootstrap/static/.  and that i could control this with configuration.

**Comment by mbr** [comment]
If you're sure, you're serving ``theme.css`` from your site, just use a regular static source, i.e. ``{{url_for('static', filename='css/style.css'}}``. You should never put any files into the static/bootstrap folder, that one is just for files shipped with Flask-Bootstrap.

The ``find_resource`` scripts are just for files that ship with the package, but can also be downloaded from a CDN. When you ask them for a file, they basically check whether you want to serve locally or from a CDN and supply an appropriate URL.

Since your own, custom resources will hardly be on a CDN, you will almost always want to use static.
