### ISSUE TITLE
required class (from 3.3.0.2) should be optional when using quick_form()

### ISSUE THREAD

**Issue by fabionorcini** [mbr/flask-bootstrap#140]
Please make this feature optional or remove it.
Adding the **required attribute** to input elements by default maybe not a good choice.
In fact this cause that some browser (i.e. chrome) trigger a clent-side validation before send the request to server. 
This **breaks** the, eventually present, complex server-side wtforms validations.

For example a custom validation that check the submission of one field against another can't be done.

Unluckily I don't have found a workarond (if not revert to previous version or manually modify wtf.htlml)

thanks for attention,
greetings

**Comment by mbr** [comment]
I'm not too happy changing anything around `quick_form`, as it should be replace at some point with a more robust solution, without breaking legacy code. One could argue that I did not listen to my own advice when I broke yours.

The `quick_form` macro is an example of an initially misunderstood functionaliy; details on that can be found in issue #74 Not adding the `required` attribute seems an ill-advised hack at this point; the `quick_form` based rendering just does not afford it in its current state.

Additionally, I think in your specific use-case, wouldn't you rather want the [novalidate](https://davidwalsh.name/novalidate) attribute? If so, this becomes an issue of setting the attribute on the `<form>` element. I'll add a way of doing so later on, so that

```
quick_form(..., novalidate=True)
```

outputs the respective tag.

---

For the future, I do see a better coming around: There is unstable functionality that is supposed to replace `quick_form` at some point. It's not documented yet though and not production ready:

```python
# ...
    password = TextField(u'Your favorite password', validators=[Required()])
    email = TextField(u'Your email address', validators=[Email()])
# ...
```

using 

```jinja
   <div class="col-md-12">
     {{form|render_form()}}
   </div>
```

yields the following HTML:

```
  <div class="form-group required">
    <!-- Field: password (TextField) -->
    <label for="password">Your favorite password</label>
    <input class="form-control" type="text">
  </div>
  <div class="form-group">
    <!-- Field: email (TextField) -->
    <label for="email">Your email address</label>
    <input class="form-control" type="email">
  </div>
```

These are based on a visitor implementation that allows overriding how things are rendered cleanly in Python.

**Comment by fabionorcini** [comment]
ok, I undertand.
novalidate property support is simply perfect for me.

Thanks many for this feature and for all your work!
Greetings
