### ISSUE TITLE
Unable to forward kwargs to SubmitField when using form_field macro

### ISSUE THREAD

**Issue by AlmogCohen** [mbr/flask-bootstrap#87]
I use angular some of the times so I use `wtf.form_field` many times.
I want to forward `ng-click=run()` but for some reason `kwargs` are not forwarded when the field type is `SubmitField ` in the `form_field` macro.

I tried to fork and fix it but my Jinja2 knowledge is not enough, thanks!

**Comment by mbr** [comment]
Without looking at the issue in particular, I think it may be an issue with
the dash. ``ng-click`` in Python would be an expression, "ng minus click"
and impossible to pass as an argument. I believe Jinja borrows quite a few
traits from Python, possibly this one as well.

There is an exception to that, I believe if you pass the parameters by
passing a dictionary, it could be possible to pass otherwise "invalid"
values.

Instead of asking for a minimal test case right away, I'd suggest you check
if the dash is an issue. Workarounds could be passing an dictionary using
**kwargs, but the most pragmatic route could be simply changing the name. I
haven't worked with angular in quite some times, but if I remember
correctly ``ng_click`` was equivalent to ``ng-click``? Maybe even
``ngClick``, I am less sure on that one though.

**Comment by AlmogCohen** [comment]
Hi mbr, I'm sure about the bug :) 
In order to use angular stuff I do:
`{{ wtf.form_field(form.query, **{'ng-model': 'query'}) }}` which works great!

I've read the code and I see that in `wtf.py` file in line 61 of the official pypi version there is that line
`{{field(class='btn btn-%s' % button_map.get(field.name, 'default'))}}`

As you can see, the kwargs are now passed to the field __call__ function.
I'm quit sure that this is the problem, but I wasn't able to just add the kwargs, because it is empty, because this line is called as in another macro `_hz_form_wrap`. I'm not sure how to fix it because I don't know enough about Jinja2 yet :)

Tnx!

**Comment by mbr** [comment]
Try 4987870 =).

**Comment by AlmogCohen** [comment]
Thanks mbr, but its not working :sob: 
I tried to do this change myself but for some reason the `kwargs` used in that line are always empty.
I think that it is because it is called inside another macro `_hz_form_wrap`.

try it yourself, it is not working:
`{{ wtf.form_field(form.submit, **{'ng-click': 'updateItems()'}) }}`

**Comment by mbr** [comment]
See #90, works will continue there.
