### ISSUE TITLE
Unable to forward kwargs to SubmitField when using form_field macro

### ISSUE THREAD

**Issue by AlmogCohen** [mbr/flask-bootstrap#90]
I've already opened this issue, but it was marked as closed although it is still not working
I just want to make sure it doesn't disappear.

The link to the bug is here:
https://github.com/mbr/flask-bootstrap/issues/87

Thanks!

**Comment by jfpoilpret** [comment]
Hi, I've got exactly the same problem here.
After some investigation, I found out that the reason why `kwargs` is always empty when passed to a `SubmitField` is because it is embedded in another call:

    {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required) %}
      {{field(class='btn btn-%s' % button_map.get(field.name, 'default'), titi='toto', **kwargs)}}
    {% endcall %}

If you echo `{{ kwargs }}` before and after `{% call _hz... %}`, you will see that it is correct before and empty after.

Further investigation led me to this quick fix in `bootstrap/wtf.html`:

    {% macro _hz_form_wrap(horizontal_columns, form_type, add_group=False, required=False) %}
    ...
    {{caller(**kwargs)}}
    ...
    {% endmacro %}


    {%- elif field.type == 'SubmitField' -%}
      {# note: same issue as above - should check widget, not field type #}
      {% call _hz_form_wrap(horizontal_columns, form_type, True, required=required, **kwargs) %}
        {{field(class='btn btn-%s' % button_map.get(field.name, 'default'), **kwargs)}}
      {% endcall %}
    ...

That makes actually two simple changes:

1. add `**kwargs` to `{{ caller() }}` inside `_hz_form_wrap` macro
2. pass `**kwargs` to `_hz_form_wrap` macro call

I haven't checked this change thoroughly but it works in my situation.
Sorry I have not patch or PR to submit as I have made the changes directly in my `Lib/site-packages` source code from pipy install.

**Comment by mbr** [comment]
It may be a scoping issue. Please try the latest commit and see if it fixes your issues.

**Comment by jfpoilpret** [comment]
Hi, thanks.
Your fix is far better than my suggested workaround. 
It works perfectly on my use case.

**Comment by mbr** [comment]
Alright, closing this then. Can't say when there'll be a release, but I'll keep the fix in mind =).
