### ISSUE TITLE
Bootstrap Flash Error

### ISSUE THREAD

**Issue by seppeduwe** [mbr/flask-bootstrap#91]
I am using macro flashed_messages from utils.html
Flask module flask-admin/user use:
```
flash(u'Invalid password provided', 'error')
```
But there exist no error alert (css class) in Bootstrap only danger. And I get a white alert.

I 'solved' it by copying alert-danger of Bootstrap CSS to my css file and changed it to alert-error
```
/**** Bootstrap flash alert Error  ****/
/**** Copy from Bootstrap alert danger  ****/
.alert-error {
  color: #a94442;
  background-color: #f2dede;
  border-color: #ebccd1;
}
.alert-error hr {
  border-top-color: #e4b9c0;
}
.alert-error .alert-link {
  color: #843534;
}
```
It can also be solve to add this in the utils.html file
```
{% if category=='error' %}
             {% set category='danger' %}
 {% endif %}
```
If other people have the same problem, could this be added to the file in next release?

Thanks

**Comment by mbr** [comment]
This seems to change the scope somewhat, as supporting all of the other extensions out there is not really a viable option. Especially since I am not exactly a fan of Flask-Admin.

I will admit that bootstrap's css classes aren't exactly standard though ("danger" comes to mind), so I will look into that.
