### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by Garito** [mbr/flask-bootstrap#99]
Hi!
I'm using bootstrap + bootswatch for themes so my question would be:
How can I integrate both with your library?
What about less usage? How do you thing would be the correct way to integrate it? By using bootstrap complete and then apply your custom styles (cascade magic) or by compiling a single file with your custom less importing boostrap less?

Thanks!

**Comment by mbr** [comment]
I have a slightly different view on how assets should be managed: No asset compilation/minimization/whatsoever on the server. I would recommend you assemble your stylesheet, javascript, image and font assets using your favorite toolchain and then embed them into the templates. Example for css:

```jinja
    {%- block styles %}
    <link href="{{url_for('.static', filename='mybootstrap.css')}}" rel="stylesheet">
    {%- endblock styles %}
```

This will replace all other stylesheets, since there is no {{super()}}. Whenever I customizes bootstrap, I compile using lessc and inherit from the bootstrap styles; I use scons and https://github.com/mbr/scons-tools for that (note that these tools are not fully polished, use at your own risk. You may be better off using off-the-shelf solutions like bower, grunt or whatever the cool kids use these days).

Javascript works the same, you may want to add a ``super`` there if you plan on using bootstrap functionality.

These are some loose thoughts, at some point I will compile them into an entry for the docs, but unfortunately I haven't gotten around to that yet.

**Comment by Garito** [comment]
I'm using the autocompiler for brackets who compile the less file into css when the editor saves a less (by using compile.json file in the root of my app)

Thanks good enought to me!
